// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/cone.glb --transform 
Files: ./public/cone.glb [17.7KB] > D:\coding-projects\3d-model-shop\cone-transformed.glb [4.46KB] (75%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cone-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.841, 1]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/cone-transformed.glb')
